spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DATABASE:localhost}:5432/playgame_store
    username: postgres
    password: 1984
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

